name: whoami_app
description: "WHOAMI Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.0+1
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  percent_indicator: ^4.2.5
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  auto_route_generator: ^10.2.3
  flutter_gen_runner: ^5.4.0
  intl_utils: ^2.8.10
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/img/png/
    - assets/img/svg/

flutter_gen:
  output: lib/gen_assets/

  integrations:
    flutter_svg: true

